---
- name: Install Node Exporter on Couchbase Servers
  hosts: all
  become: yes  # Required for privilege escalation

  tasks:
    - name: Download Node Exporter
      get_url:
        url: "https://github.com/prometheus/node_exporter/releases/download/v1.7.0/node_exporter-1.7.0.linux-amd64.tar.gz"
        dest: "/tmp/node_exporter.tar.gz"

    - name: Ensure node_exporter user and group exist
      block:
        - name: Create node_exporter group
          group:
            name: node_exporter
            state: present

        - name: Create node_exporter user
          user:
            name: node_exporter
            group: node_exporter
            createhome: no
            shell: /bin/false

    - name: Create directories
      file:
        path: "{{ item }}"
        state: directory
        owner: node_exporter
        group: node_exporter
      loop:
        - /etc/node_exporter

    - name: Unpack Node Exporter binary
      unarchive:
        src: "/tmp/node_exporter-1.7.0.linux-amd64.tar.gz"
        dest: "/tmp"
        remote_src: yes
        creates: "/tmp/node_exporter-1.7.0.linux-amd64/node_exporter"

    - name: Install Node Exporter binary
      ansible.builtin.copy:
       src: "/tmp/node_exporter-1.7.0.linux-amd64/node_exporter"
       dest: "/usr/bin/node_exporter"
       owner: node_exporter
       group: node_exporter
       mode: '0755'
       remote_src: yes

    - name: Setup Node Exporter service
      copy:
        dest: "/usr/lib/systemd/system/node_exporter.service"
        content: |
          [Unit]
          Description=Node Exporter
          Documentation=https://prometheus.io/docs/guides/node-exporter/
          Wants=network-online.target
          After=network-online.target

          [Service]
          User=node_exporter
          Group=node_exporter
          Type=simple
          Restart=on-failure
          ExecStart=/usr/bin/node_exporter --web.listen-address=:3000

          [Install]
          WantedBy=multi-user.target
        mode: '0664'

    - name: Reload systemd, enable and start Node Exporter
      systemd:
        name: node_exporter
        daemon_reload: yes
        enabled: yes
        state: started

    - name: Clean up download and temporary files
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - "/tmp/node_exporter.tar.gz"
        - "/tmp/node_exporter-1.7.0.linux-amd64"
